CREATE TABLE `coches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `marca` varchar(50) NOT NULL,
  `modelo` varchar(50) NOT NULL,
  `precio` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;


insert into coches (marca, modelo, precio) values ('Chevrolet', 'Venture', 31708);
insert into coches (marca, modelo, precio) values ('Volvo', 'C70', 19771);
insert into coches (marca, modelo, precio) values ('Lexus', 'ES', 20101);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Caprice Classic', 32187);
insert into coches (marca, modelo, precio) values ('Pontiac', 'LeMans', 37278);
insert into coches (marca, modelo, precio) values ('Buick', 'LeSabre', 12903);
insert into coches (marca, modelo, precio) values ('BMW', 'Z3', 26619);
insert into coches (marca, modelo, precio) values ('Lincoln', 'Aviator', 10428);
insert into coches (marca, modelo, precio) values ('BMW', '5 Series', 44813);
insert into coches (marca, modelo, precio) values ('GMC', 'Sierra 3500', 44297);
insert into coches (marca, modelo, precio) values ('Acura', 'TL', 47518);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Silverado 3500', 34434);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Bonneville', 39450);
insert into coches (marca, modelo, precio) values ('Mazda', '626', 10158);
insert into coches (marca, modelo, precio) values ('Ford', 'E-Series', 19902);
insert into coches (marca, modelo, precio) values ('BMW', '650', 23434);
insert into coches (marca, modelo, precio) values ('Ford', 'F-350 Super Duty', 21985);
insert into coches (marca, modelo, precio) values ('Buick', 'Century', 22173);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Expo', 40616);
insert into coches (marca, modelo, precio) values ('Toyota', 'T100', 34204);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Impala', 47983);
insert into coches (marca, modelo, precio) values ('Lexus', 'RX', 19127);
insert into coches (marca, modelo, precio) values ('Nissan', '300ZX', 15594);
insert into coches (marca, modelo, precio) values ('Lincoln', 'Continental', 10323);
insert into coches (marca, modelo, precio) values ('Toyota', 'Highlander', 14382);
insert into coches (marca, modelo, precio) values ('Pontiac', 'GTO', 26545);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'New Beetle', 43975);
insert into coches (marca, modelo, precio) values ('Nissan', '350Z', 33347);
insert into coches (marca, modelo, precio) values ('Nissan', 'Altima', 16159);
insert into coches (marca, modelo, precio) values ('Saturn', 'L-Series', 41241);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Suburban', 25587);
insert into coches (marca, modelo, precio) values ('Chrysler', 'Concorde', 24645);
insert into coches (marca, modelo, precio) values ('Mazda', 'MX-6', 46415);
insert into coches (marca, modelo, precio) values ('Ford', 'Thunderbird', 18662);
insert into coches (marca, modelo, precio) values ('Dodge', 'Ram Wagon B250', 25447);
insert into coches (marca, modelo, precio) values ('Isuzu', 'Ascender', 12171);
insert into coches (marca, modelo, precio) values ('Studebaker', 'Avanti', 39529);
insert into coches (marca, modelo, precio) values ('Nissan', 'Sentra', 12244);
insert into coches (marca, modelo, precio) values ('Infiniti', 'G', 14618);
insert into coches (marca, modelo, precio) values ('GMC', 'Suburban 1500', 44220);
insert into coches (marca, modelo, precio) values ('Volvo', 'V70', 15561);
insert into coches (marca, modelo, precio) values ('Plymouth', 'Grand Voyager', 45335);
insert into coches (marca, modelo, precio) values ('Mazda', 'Mazda3', 44715);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Corvette', 35118);
insert into coches (marca, modelo, precio) values ('Ford', 'E-Series', 11030);
insert into coches (marca, modelo, precio) values ('Mercury', 'Villager', 32388);
insert into coches (marca, modelo, precio) values ('Jaguar', 'XJ', 10218);
insert into coches (marca, modelo, precio) values ('Jaguar', 'XK Series', 48467);
insert into coches (marca, modelo, precio) values ('Dodge', 'Colt', 12009);
insert into coches (marca, modelo, precio) values ('Ford', 'Ranger', 19926);
insert into coches (marca, modelo, precio) values ('GMC', '2500 Club Coupe', 41962);
insert into coches (marca, modelo, precio) values ('Ford', 'Club Wagon', 11820);
insert into coches (marca, modelo, precio) values ('Saturn', 'S-Series', 13075);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Corvette', 31378);
insert into coches (marca, modelo, precio) values ('Ford', 'Escape', 40418);
insert into coches (marca, modelo, precio) values ('Cadillac', 'Escalade EXT', 47092);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Express 2500', 28728);
insert into coches (marca, modelo, precio) values ('Ford', 'ZX2', 12296);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'GLK-Class', 44008);
insert into coches (marca, modelo, precio) values ('Pontiac', 'GTO', 46608);
insert into coches (marca, modelo, precio) values ('Dodge', 'Caravan', 46389);
insert into coches (marca, modelo, precio) values ('Cadillac', 'Eldorado', 39971);
insert into coches (marca, modelo, precio) values ('Mazda', 'MX-5', 11050);
insert into coches (marca, modelo, precio) values ('GMC', 'Sonoma', 39429);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'GTI', 39696);
insert into coches (marca, modelo, precio) values ('Mercury', 'Mariner', 44292);
insert into coches (marca, modelo, precio) values ('Lincoln', 'Town Car', 48793);
insert into coches (marca, modelo, precio) values ('Ford', 'Transit Connect', 16559);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Suburban 2500', 48197);
insert into coches (marca, modelo, precio) values ('Ford', 'Escort', 47464);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'GTI', 48113);
insert into coches (marca, modelo, precio) values ('Honda', 'Civic Si', 49691);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'SL-Class', 27762);
insert into coches (marca, modelo, precio) values ('Subaru', 'Outback', 23681);
insert into coches (marca, modelo, precio) values ('Honda', 'Civic', 10414);
insert into coches (marca, modelo, precio) values ('Kia', 'Amanti', 24906);
insert into coches (marca, modelo, precio) values ('Mercury', 'Cougar', 47803);
insert into coches (marca, modelo, precio) values ('Nissan', 'Maxima', 16262);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Cavalier', 16068);
insert into coches (marca, modelo, precio) values ('Chrysler', 'Aspen', 45920);
insert into coches (marca, modelo, precio) values ('GMC', 'Acadia', 31292);
insert into coches (marca, modelo, precio) values ('Isuzu', 'Rodeo', 34896);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Corvette', 17779);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Galant', 17028);
insert into coches (marca, modelo, precio) values ('Pontiac', '6000', 35357);
insert into coches (marca, modelo, precio) values ('GMC', 'Savana', 13742);
insert into coches (marca, modelo, precio) values ('Toyota', 'MR2', 14341);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Bonneville', 41056);
insert into coches (marca, modelo, precio) values ('Jeep', 'Grand Cherokee', 34462);
insert into coches (marca, modelo, precio) values ('Lincoln', 'Navigator', 43528);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Corvette', 13806);
insert into coches (marca, modelo, precio) values ('Pontiac', 'LeMans', 20350);
insert into coches (marca, modelo, precio) values ('Lincoln', 'Aviator', 13284);
insert into coches (marca, modelo, precio) values ('GMC', 'Jimmy', 38204);
insert into coches (marca, modelo, precio) values ('Ford', 'Crown Victoria', 10851);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'C-Class', 48690);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Aveo', 38766);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Venture', 28698);
insert into coches (marca, modelo, precio) values ('Mazda', 'MX-5', 47904);
insert into coches (marca, modelo, precio) values ('Saab', '900', 28604);
insert into coches (marca, modelo, precio) values ('Dodge', 'Journey', 49579);
insert into coches (marca, modelo, precio) values ('Isuzu', 'Ascender', 28414);
insert into coches (marca, modelo, precio) values ('Audi', '80/90', 39607);
insert into coches (marca, modelo, precio) values ('BMW', 'Z4', 19431);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'Cabriolet', 40488);
insert into coches (marca, modelo, precio) values ('Volvo', 'XC70', 18044);
insert into coches (marca, modelo, precio) values ('GMC', 'Sierra 2500', 37037);
insert into coches (marca, modelo, precio) values ('Dodge', 'Dakota Club', 17180);
insert into coches (marca, modelo, precio) values ('Nissan', '370Z', 31066);
insert into coches (marca, modelo, precio) values ('Honda', 'Element', 26328);
insert into coches (marca, modelo, precio) values ('GMC', 'Acadia', 23095);
insert into coches (marca, modelo, precio) values ('Acura', 'NSX', 22833);
insert into coches (marca, modelo, precio) values ('Oldsmobile', 'Bravada', 13010);
insert into coches (marca, modelo, precio) values ('Scion', 'iQ', 30946);
insert into coches (marca, modelo, precio) values ('Saturn', 'S-Series', 40563);
insert into coches (marca, modelo, precio) values ('Ford', 'Explorer', 24389);
insert into coches (marca, modelo, precio) values ('Saab', '9-2X', 19147);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'Touareg 2', 17054);
insert into coches (marca, modelo, precio) values ('Infiniti', 'G', 11543);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Avalanche 2500', 30985);
insert into coches (marca, modelo, precio) values ('Maserati', 'Gran Sport', 11703);
insert into coches (marca, modelo, precio) values ('GMC', 'Vandura G1500', 40359);
insert into coches (marca, modelo, precio) values ('Lexus', 'LS', 23512);
insert into coches (marca, modelo, precio) values ('Mercury', 'Grand Marquis', 43882);
insert into coches (marca, modelo, precio) values ('GMC', 'Yukon XL 2500', 27711);
insert into coches (marca, modelo, precio) values ('Saturn', 'Aura', 29511);
insert into coches (marca, modelo, precio) values ('Jeep', 'Patriot', 26866);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Pajero', 42742);
insert into coches (marca, modelo, precio) values ('Cadillac', 'Seville', 27956);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Firebird', 31388);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'R32', 23648);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Express 1500', 36050);
insert into coches (marca, modelo, precio) values ('Subaru', 'Forester', 15486);
insert into coches (marca, modelo, precio) values ('Ford', 'Galaxie', 26275);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Silverado 3500', 35599);
insert into coches (marca, modelo, precio) values ('Subaru', 'XT', 41507);
insert into coches (marca, modelo, precio) values ('Lamborghini', 'Countach', 14034);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Silverado 1500', 42604);
insert into coches (marca, modelo, precio) values ('Suzuki', 'Sidekick', 32807);
insert into coches (marca, modelo, precio) values ('Mazda', 'B-Series', 27731);
insert into coches (marca, modelo, precio) values ('GMC', 'Sierra 1500', 27380);
insert into coches (marca, modelo, precio) values ('Kia', 'Sedona', 21237);
insert into coches (marca, modelo, precio) values ('BMW', '1 Series', 23022);
insert into coches (marca, modelo, precio) values ('GMC', 'Terrain', 31394);
insert into coches (marca, modelo, precio) values ('Bentley', 'Arnage', 14539);
insert into coches (marca, modelo, precio) values ('Mercury', 'Mountaineer', 25089);
insert into coches (marca, modelo, precio) values ('Honda', 'CR-X', 16077);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Expo', 31948);
insert into coches (marca, modelo, precio) values ('Ford', 'Laser', 39214);
insert into coches (marca, modelo, precio) values ('Nissan', 'Pathfinder Armada', 39875);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Suburban 2500', 47526);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Avalanche', 38812);
insert into coches (marca, modelo, precio) values ('Suzuki', 'Grand Vitara', 11018);
insert into coches (marca, modelo, precio) values ('Chevrolet', '1500', 17004);
insert into coches (marca, modelo, precio) values ('Dodge', 'Journey', 17191);
insert into coches (marca, modelo, precio) values ('Ford', 'Ranger', 47636);
insert into coches (marca, modelo, precio) values ('Mercury', 'Tracer', 23640);
insert into coches (marca, modelo, precio) values ('Toyota', 'RAV4', 23156);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Cordia', 23175);
insert into coches (marca, modelo, precio) values ('Hummer', 'H1', 29139);
insert into coches (marca, modelo, precio) values ('Lincoln', 'Town Car', 11361);
insert into coches (marca, modelo, precio) values ('Dodge', 'Ram Van 3500', 19374);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Silverado 2500', 36053);
insert into coches (marca, modelo, precio) values ('Honda', 'CR-V', 30159);
insert into coches (marca, modelo, precio) values ('Toyota', 'Supra', 25250);
insert into coches (marca, modelo, precio) values ('Ford', 'Thunderbird', 15281);
insert into coches (marca, modelo, precio) values ('GMC', 'Sonoma', 21684);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Galant', 43593);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'TrailBlazer', 40373);
insert into coches (marca, modelo, precio) values ('Ford', 'F250', 36662);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'W126', 20589);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Diamante', 46235);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'CL-Class', 28857);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Camaro', 34301);
insert into coches (marca, modelo, precio) values ('Bentley', 'Arnage', 41601);
insert into coches (marca, modelo, precio) values ('Mazda', 'B-Series Plus', 10827);
insert into coches (marca, modelo, precio) values ('BMW', 'X6 M', 18098);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Endeavor', 45405);
insert into coches (marca, modelo, precio) values ('Ford', 'Taurus', 15637);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'Touareg', 13269);
insert into coches (marca, modelo, precio) values ('Ford', 'Tempo', 10998);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Outlander', 43276);
insert into coches (marca, modelo, precio) values ('Ford', 'Aspire', 15652);
insert into coches (marca, modelo, precio) values ('Land Rover', 'Range Rover', 13598);
insert into coches (marca, modelo, precio) values ('Kia', 'Sportage', 23949);
insert into coches (marca, modelo, precio) values ('Land Rover', 'Freelander', 42245);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Firefly', 19532);
insert into coches (marca, modelo, precio) values ('Ford', 'Focus', 25954);
insert into coches (marca, modelo, precio) values ('Saturn', 'L-Series', 40982);
insert into coches (marca, modelo, precio) values ('Nissan', 'Versa', 47911);
insert into coches (marca, modelo, precio) values ('Subaru', 'Outback', 11670);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'Touareg 2', 48510);
insert into coches (marca, modelo, precio) values ('Mazda', 'Mazda6', 35512);
insert into coches (marca, modelo, precio) values ('Toyota', 'Corolla', 28723);
insert into coches (marca, modelo, precio) values ('Holden', 'VS Commodore', 27028);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Corsica', 29107);
insert into coches (marca, modelo, precio) values ('GMC', 'Envoy', 30283);
insert into coches (marca, modelo, precio) values ('Scion', 'tC', 18950);
insert into coches (marca, modelo, precio) values ('Hyundai', 'Elantra', 34420);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Express 1500', 28368);
insert into coches (marca, modelo, precio) values ('Dodge', 'Daytona', 44708);
insert into coches (marca, modelo, precio) values ('BMW', 'M3', 47493);
insert into coches (marca, modelo, precio) values ('Porsche', '911', 36033);
insert into coches (marca, modelo, precio) values ('Buick', 'Skyhawk', 49385);
insert into coches (marca, modelo, precio) values ('Nissan', '240SX', 42551);
insert into coches (marca, modelo, precio) values ('Kia', 'Rondo', 33723);
insert into coches (marca, modelo, precio) values ('Toyota', 'Land Cruiser', 40989);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', '300TE', 15246);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Impala', 43337);
insert into coches (marca, modelo, precio) values ('Cadillac', 'CTS', 34594);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'CL-Class', 31328);
insert into coches (marca, modelo, precio) values ('Honda', 'FCX Clarity', 34506);
insert into coches (marca, modelo, precio) values ('Mazda', 'Mazda6 5-Door', 17303);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Chariot', 39855);
insert into coches (marca, modelo, precio) values ('Saab', '900', 28622);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Grand Prix', 37663);
insert into coches (marca, modelo, precio) values ('Ford', 'Econoline E250', 16278);
insert into coches (marca, modelo, precio) values ('Eagle', 'Talon', 49172);
insert into coches (marca, modelo, precio) values ('Acura', 'TSX', 20627);
insert into coches (marca, modelo, precio) values ('BMW', 'Z8', 26042);
insert into coches (marca, modelo, precio) values ('Jaguar', 'XK', 31109);
insert into coches (marca, modelo, precio) values ('Hyundai', 'HED-5', 19456);
insert into coches (marca, modelo, precio) values ('GMC', 'Vandura 1500', 35621);
insert into coches (marca, modelo, precio) values ('Lexus', 'RX Hybrid', 21703);
insert into coches (marca, modelo, precio) values ('Lexus', 'ES', 30333);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Eclipse', 32935);
insert into coches (marca, modelo, precio) values ('Isuzu', 'i-370', 18699);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'E-Class', 31977);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Bonneville', 29934);
insert into coches (marca, modelo, precio) values ('Toyota', 'Xtra', 48849);
insert into coches (marca, modelo, precio) values ('Audi', 'A8', 33069);
insert into coches (marca, modelo, precio) values ('Lexus', 'SC', 25808);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Eclipse', 30521);
insert into coches (marca, modelo, precio) values ('Infiniti', 'G35', 42686);
insert into coches (marca, modelo, precio) values ('Infiniti', 'M', 18433);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Corvette', 43158);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Grand Prix', 14341);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'Cabriolet', 29481);
insert into coches (marca, modelo, precio) values ('Maserati', 'Spyder', 47793);
insert into coches (marca, modelo, precio) values ('BMW', 'X6 M', 49287);
insert into coches (marca, modelo, precio) values ('Mazda', 'B-Series', 42708);
insert into coches (marca, modelo, precio) values ('GMC', 'Sierra 2500', 29966);
insert into coches (marca, modelo, precio) values ('Dodge', 'Ram Van B350', 15769);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Lancer', 18380);
insert into coches (marca, modelo, precio) values ('GMC', 'Savana 3500', 29153);
insert into coches (marca, modelo, precio) values ('GMC', 'Suburban 2500', 46294);
insert into coches (marca, modelo, precio) values ('Mercury', 'Cougar', 48647);
insert into coches (marca, modelo, precio) values ('Subaru', 'SVX', 38066);
insert into coches (marca, modelo, precio) values ('GMC', 'Suburban 1500', 42071);
insert into coches (marca, modelo, precio) values ('Cadillac', 'Eldorado', 22746);
insert into coches (marca, modelo, precio) values ('Toyota', 'Celica', 48650);
insert into coches (marca, modelo, precio) values ('Dodge', 'Viper RT/10', 47707);
insert into coches (marca, modelo, precio) values ('Mazda', 'Tribute', 35522);
insert into coches (marca, modelo, precio) values ('Audi', 'S6', 40464);
insert into coches (marca, modelo, precio) values ('Ford', 'Transit Connect', 21362);
insert into coches (marca, modelo, precio) values ('Audi', 'A5', 49739);
insert into coches (marca, modelo, precio) values ('Cadillac', 'SRX', 11635);
insert into coches (marca, modelo, precio) values ('Maserati', 'Spyder', 16176);
insert into coches (marca, modelo, precio) values ('Ford', 'F150', 21774);
insert into coches (marca, modelo, precio) values ('Eagle', 'Summit', 17941);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Express 3500', 16823);
insert into coches (marca, modelo, precio) values ('Ford', 'Ranger', 12967);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Avalanche 1500', 46239);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Express 3500', 15912);
insert into coches (marca, modelo, precio) values ('Lincoln', 'Continental Mark VII', 44942);
insert into coches (marca, modelo, precio) values ('Ford', 'Thunderbird', 20789);
insert into coches (marca, modelo, precio) values ('Audi', 'TT', 15694);
insert into coches (marca, modelo, precio) values ('Plymouth', 'Voyager', 18797);
insert into coches (marca, modelo, precio) values ('GMC', 'Envoy', 24798);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Silverado 3500', 40747);
insert into coches (marca, modelo, precio) values ('Mazda', '929', 22315);
insert into coches (marca, modelo, precio) values ('Lexus', 'RX', 14501);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', '300SL', 44625);
insert into coches (marca, modelo, precio) values ('Hyundai', 'Elantra', 48354);
insert into coches (marca, modelo, precio) values ('Ford', 'Thunderbird', 20351);
insert into coches (marca, modelo, precio) values ('Chrysler', 'Sebring', 37607);
insert into coches (marca, modelo, precio) values ('Chrysler', 'Pacifica', 18032);
insert into coches (marca, modelo, precio) values ('Kia', 'Rio', 20950);
insert into coches (marca, modelo, precio) values ('Jaguar', 'XJ Series', 30537);
insert into coches (marca, modelo, precio) values ('Ford', 'Fiesta', 16210);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Traverse', 25596);
insert into coches (marca, modelo, precio) values ('Cadillac', 'Escalade ESV', 23729);
insert into coches (marca, modelo, precio) values ('Toyota', 'Yaris', 24476);
insert into coches (marca, modelo, precio) values ('Infiniti', 'QX', 24756);
insert into coches (marca, modelo, precio) values ('BMW', '8 Series', 24578);
insert into coches (marca, modelo, precio) values ('Hyundai', 'Elantra', 21955);
insert into coches (marca, modelo, precio) values ('Chrysler', 'Town & Country', 45720);
insert into coches (marca, modelo, precio) values ('Ford', 'Mustang', 23584);
insert into coches (marca, modelo, precio) values ('Volvo', 'S60', 26556);
insert into coches (marca, modelo, precio) values ('Toyota', 'Matrix', 47247);
insert into coches (marca, modelo, precio) values ('MINI', 'Cooper', 31395);
insert into coches (marca, modelo, precio) values ('MINI', 'Cooper', 11534);
insert into coches (marca, modelo, precio) values ('Infiniti', 'M', 15068);
insert into coches (marca, modelo, precio) values ('Isuzu', 'Trooper', 21481);
insert into coches (marca, modelo, precio) values ('Ford', 'Windstar', 25737);
insert into coches (marca, modelo, precio) values ('Toyota', 'Land Cruiser', 45197);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Silverado 3500', 30469);
insert into coches (marca, modelo, precio) values ('GMC', 'Canyon', 12156);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Corsica', 44787);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Equinox', 48672);
insert into coches (marca, modelo, precio) values ('Subaru', 'Forester', 10621);
insert into coches (marca, modelo, precio) values ('Holden', 'VS Commodore', 27959);
insert into coches (marca, modelo, precio) values ('Nissan', 'Altima', 30228);
insert into coches (marca, modelo, precio) values ('Audi', 'S4', 22262);
insert into coches (marca, modelo, precio) values ('Mazda', 'MX-5', 14235);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Metro', 11799);
insert into coches (marca, modelo, precio) values ('Oldsmobile', 'Achieva', 16683);
insert into coches (marca, modelo, precio) values ('Toyota', 'Sienna', 33828);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Express 1500', 29614);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Venture', 10153);
insert into coches (marca, modelo, precio) values ('Chrysler', 'Fifth Ave', 46783);
insert into coches (marca, modelo, precio) values ('Kia', 'Optima', 19770);
insert into coches (marca, modelo, precio) values ('Ford', 'E-Series', 19310);
insert into coches (marca, modelo, precio) values ('Toyota', 'Avalon', 44845);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Silverado 3500', 10476);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Firefly', 16274);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'S-Class', 44655);
insert into coches (marca, modelo, precio) values ('Subaru', 'Impreza', 41809);
insert into coches (marca, modelo, precio) values ('Mercury', 'Mystique', 17969);
insert into coches (marca, modelo, precio) values ('Pontiac', 'LeMans', 42679);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Impala', 15057);
insert into coches (marca, modelo, precio) values ('GMC', 'Suburban 1500', 49628);
insert into coches (marca, modelo, precio) values ('GMC', 'Sierra 1500', 44116);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Malibu', 41128);
insert into coches (marca, modelo, precio) values ('Chrysler', '300', 19732);
insert into coches (marca, modelo, precio) values ('Toyota', 'Sienna', 31756);
insert into coches (marca, modelo, precio) values ('GMC', 'Sierra 3500', 34441);
insert into coches (marca, modelo, precio) values ('Toyota', 'Avalon', 17908);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Express 2500', 12468);
insert into coches (marca, modelo, precio) values ('Eagle', 'Talon', 41414);
insert into coches (marca, modelo, precio) values ('Infiniti', 'G', 41687);
insert into coches (marca, modelo, precio) values ('Dodge', 'Dakota Club', 26276);
insert into coches (marca, modelo, precio) values ('Mazda', '626', 21891);
insert into coches (marca, modelo, precio) values ('Jeep', 'Wrangler', 21043);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'GTO', 46809);
insert into coches (marca, modelo, precio) values ('Toyota', 'Tundra', 23043);
insert into coches (marca, modelo, precio) values ('Mercury', 'Capri', 49547);
insert into coches (marca, modelo, precio) values ('Ford', 'Freestar', 29029);
insert into coches (marca, modelo, precio) values ('Lexus', 'ES', 43404);
insert into coches (marca, modelo, precio) values ('BMW', '5 Series', 14322);
insert into coches (marca, modelo, precio) values ('Land Rover', 'Defender 110', 43974);
insert into coches (marca, modelo, precio) values ('GMC', 'Savana 1500', 13617);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'CLS-Class', 21992);
insert into coches (marca, modelo, precio) values ('Toyota', '4Runner', 33237);
insert into coches (marca, modelo, precio) values ('BMW', '3 Series', 43745);
insert into coches (marca, modelo, precio) values ('Lamborghini', 'Gallardo', 36500);
insert into coches (marca, modelo, precio) values ('Jaguar', 'XJ', 34094);
insert into coches (marca, modelo, precio) values ('Audi', 'TT', 24502);
insert into coches (marca, modelo, precio) values ('Volvo', 'XC90', 19321);
insert into coches (marca, modelo, precio) values ('Jeep', 'Wrangler', 33012);
insert into coches (marca, modelo, precio) values ('Audi', 'S4', 40103);
insert into coches (marca, modelo, precio) values ('Lincoln', 'MKZ', 30594);
insert into coches (marca, modelo, precio) values ('Ford', 'Explorer Sport Trac', 33851);
insert into coches (marca, modelo, precio) values ('Toyota', 'MR2', 28742);
insert into coches (marca, modelo, precio) values ('Daewoo', 'Lanos', 24723);
insert into coches (marca, modelo, precio) values ('Oldsmobile', 'Achieva', 43181);
insert into coches (marca, modelo, precio) values ('Suzuki', 'Sidekick', 47168);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'CL-Class', 31057);
insert into coches (marca, modelo, precio) values ('Toyota', 'Sienna', 43325);
insert into coches (marca, modelo, precio) values ('Acura', 'TSX', 12401);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Bonneville', 18579);
insert into coches (marca, modelo, precio) values ('Dodge', 'Ram Van 2500', 25306);
insert into coches (marca, modelo, precio) values ('Jaguar', 'XK Series', 28250);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Precis', 11181);
insert into coches (marca, modelo, precio) values ('Fairthorpe', 'Rockette', 33205);
insert into coches (marca, modelo, precio) values ('Porsche', '911', 15799);
insert into coches (marca, modelo, precio) values ('Ford', 'F450', 14674);
insert into coches (marca, modelo, precio) values ('Toyota', 'Land Cruiser', 17736);
insert into coches (marca, modelo, precio) values ('Jeep', 'Grand Cherokee', 43302);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Grand Prix', 49467);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Cobalt', 30343);
insert into coches (marca, modelo, precio) values ('Mazda', 'MX-5', 21693);
insert into coches (marca, modelo, precio) values ('Ford', 'F-Series Super Duty', 44742);
insert into coches (marca, modelo, precio) values ('GMC', 'Sonoma Club Coupe', 10588);
insert into coches (marca, modelo, precio) values ('GMC', 'Suburban 2500', 35274);
insert into coches (marca, modelo, precio) values ('Suzuki', 'XL-7', 15127);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Express', 40772);
insert into coches (marca, modelo, precio) values ('Toyota', 'Sequoia', 27143);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'S-Class', 12801);
insert into coches (marca, modelo, precio) values ('Ford', 'EXP', 11094);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Diamante', 23683);
insert into coches (marca, modelo, precio) values ('Suzuki', 'Sidekick', 48596);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Bonneville', 11453);
insert into coches (marca, modelo, precio) values ('Mazda', '626', 47318);
insert into coches (marca, modelo, precio) values ('MINI', 'Clubman', 18950);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Colorado', 13730);
insert into coches (marca, modelo, precio) values ('GMC', 'Sonoma', 14047);
insert into coches (marca, modelo, precio) values ('Dodge', 'Ram 2500', 46474);
insert into coches (marca, modelo, precio) values ('Mazda', 'Mazda6 Sport', 16829);
insert into coches (marca, modelo, precio) values ('GMC', 'Sierra 2500', 48300);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Grand Prix', 42294);
insert into coches (marca, modelo, precio) values ('Dodge', 'Grand Caravan', 25424);
insert into coches (marca, modelo, precio) values ('Infiniti', 'J', 24943);
insert into coches (marca, modelo, precio) values ('Ford', 'F350', 41760);
insert into coches (marca, modelo, precio) values ('Lexus', 'ES', 44207);
insert into coches (marca, modelo, precio) values ('Ford', 'E-Series', 25513);
insert into coches (marca, modelo, precio) values ('Ford', 'Econoline E150', 48110);
insert into coches (marca, modelo, precio) values ('Mazda', 'MPV', 22892);
insert into coches (marca, modelo, precio) values ('Buick', 'LeSabre', 35348);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'L300', 38099);
insert into coches (marca, modelo, precio) values ('Lincoln', 'Navigator', 27476);
insert into coches (marca, modelo, precio) values ('GMC', 'Jimmy', 44223);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Corsica', 40148);
insert into coches (marca, modelo, precio) values ('BMW', '760', 19613);
insert into coches (marca, modelo, precio) values ('Lamborghini', 'Gallardo', 10931);
insert into coches (marca, modelo, precio) values ('Daihatsu', 'Rocky', 24714);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Firefly', 31845);
insert into coches (marca, modelo, precio) values ('Aston Martin', 'Vanquish S', 12824);
insert into coches (marca, modelo, precio) values ('Ford', 'Explorer', 48331);
insert into coches (marca, modelo, precio) values ('Volvo', 'V70', 32121);
insert into coches (marca, modelo, precio) values ('Ford', 'Crown Victoria', 19578);
insert into coches (marca, modelo, precio) values ('Dodge', 'Viper', 35364);
insert into coches (marca, modelo, precio) values ('Ford', 'Thunderbird', 30545);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Firebird Formula', 27947);
insert into coches (marca, modelo, precio) values ('Buick', 'Riviera', 48853);
insert into coches (marca, modelo, precio) values ('Mercury', 'Cougar', 37966);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'Eurovan', 43793);
insert into coches (marca, modelo, precio) values ('GMC', '1500', 38915);
insert into coches (marca, modelo, precio) values ('Eagle', 'Vision', 20410);
insert into coches (marca, modelo, precio) values ('Kia', 'Optima', 22928);
insert into coches (marca, modelo, precio) values ('Saturn', 'VUE', 32656);
insert into coches (marca, modelo, precio) values ('Mazda', 'MX-6', 45886);
insert into coches (marca, modelo, precio) values ('Ford', 'GT', 27668);
insert into coches (marca, modelo, precio) values ('Nissan', 'Quest', 18782);
insert into coches (marca, modelo, precio) values ('Infiniti', 'FX', 13320);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'APV', 27163);
insert into coches (marca, modelo, precio) values ('Mazda', 'Mazda5', 39091);
insert into coches (marca, modelo, precio) values ('Panoz', 'Esperante', 48866);
insert into coches (marca, modelo, precio) values ('GMC', 'Suburban 1500', 39306);
insert into coches (marca, modelo, precio) values ('Dodge', 'Sprinter', 38522);
insert into coches (marca, modelo, precio) values ('GMC', 'Yukon XL 1500', 17113);
insert into coches (marca, modelo, precio) values ('Honda', 'Accord', 16939);
insert into coches (marca, modelo, precio) values ('Toyota', 'Tacoma Xtra', 12105);
insert into coches (marca, modelo, precio) values ('Ford', 'Econoline E150', 45001);
insert into coches (marca, modelo, precio) values ('Audi', '80', 32555);
insert into coches (marca, modelo, precio) values ('Toyota', 'Paseo', 27572);
insert into coches (marca, modelo, precio) values ('Mercury', 'Capri', 16500);
insert into coches (marca, modelo, precio) values ('Toyota', 'Tercel', 21960);
insert into coches (marca, modelo, precio) values ('Ford', 'LTD Crown Victoria', 16587);
insert into coches (marca, modelo, precio) values ('Ford', 'Probe', 21521);
insert into coches (marca, modelo, precio) values ('Ford', 'Aspire', 42776);
insert into coches (marca, modelo, precio) values ('Rolls-Royce', 'Ghost', 33563);
insert into coches (marca, modelo, precio) values ('Dodge', 'D350', 30672);
insert into coches (marca, modelo, precio) values ('Hyundai', 'Excel', 38325);
insert into coches (marca, modelo, precio) values ('Aston Martin', 'DBS', 36674);
insert into coches (marca, modelo, precio) values ('Fairthorpe', 'Rockette', 25169);
insert into coches (marca, modelo, precio) values ('Volkswagen', 'Jetta', 32886);
insert into coches (marca, modelo, precio) values ('Subaru', 'Baja', 17956);
insert into coches (marca, modelo, precio) values ('Chrysler', 'PT Cruiser', 47134);
insert into coches (marca, modelo, precio) values ('Lexus', 'SC', 48296);
insert into coches (marca, modelo, precio) values ('Porsche', 'Boxster', 46124);
insert into coches (marca, modelo, precio) values ('Acura', 'TL', 18840);
insert into coches (marca, modelo, precio) values ('Chrysler', 'Town & Country', 42412);
insert into coches (marca, modelo, precio) values ('Toyota', 'Avalon', 19165);
insert into coches (marca, modelo, precio) values ('Nissan', 'Maxima', 21462);
insert into coches (marca, modelo, precio) values ('GMC', 'Sierra 1500', 23220);
insert into coches (marca, modelo, precio) values ('Toyota', 'Solara', 16812);
insert into coches (marca, modelo, precio) values ('Suzuki', 'Daewoo Lacetti', 27601);
insert into coches (marca, modelo, precio) values ('Acura', 'Vigor', 23972);
insert into coches (marca, modelo, precio) values ('Suzuki', 'SJ', 48627);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'SLR McLaren', 18706);
insert into coches (marca, modelo, precio) values ('Lexus', 'CT', 26093);
insert into coches (marca, modelo, precio) values ('Mercedes-Benz', 'G-Class', 37846);
insert into coches (marca, modelo, precio) values ('Honda', 'Odyssey', 36000);
insert into coches (marca, modelo, precio) values ('Volvo', 'XC70', 28200);
insert into coches (marca, modelo, precio) values ('Buick', 'Roadmaster', 22050);
insert into coches (marca, modelo, precio) values ('Ford', 'Expedition', 17302);
insert into coches (marca, modelo, precio) values ('Lincoln', 'Continental', 46135);
insert into coches (marca, modelo, precio) values ('Ford', 'Fusion', 31126);
insert into coches (marca, modelo, precio) values ('Ford', 'Country', 12882);
insert into coches (marca, modelo, precio) values ('BMW', '6 Series', 23496);
insert into coches (marca, modelo, precio) values ('Saturn', 'Ion', 40051);
insert into coches (marca, modelo, precio) values ('Acura', 'RL', 17436);
insert into coches (marca, modelo, precio) values ('Mazda', 'MX-3', 48232);
insert into coches (marca, modelo, precio) values ('Chrysler', 'Town & Country', 19637);
insert into coches (marca, modelo, precio) values ('Land Rover', 'Range Rover', 34080);
insert into coches (marca, modelo, precio) values ('Scion', 'xB', 33653);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Impala SS', 27713);
insert into coches (marca, modelo, precio) values ('Pontiac', 'G3', 11755);
insert into coches (marca, modelo, precio) values ('Subaru', 'Impreza', 21259);
insert into coches (marca, modelo, precio) values ('Ford', 'Expedition', 49191);
insert into coches (marca, modelo, precio) values ('Chevrolet', 'Corvette', 34429);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Solstice', 20308);
insert into coches (marca, modelo, precio) values ('Cadillac', 'XLR', 45942);
insert into coches (marca, modelo, precio) values ('Hyundai', 'Genesis Coupe', 27643);
insert into coches (marca, modelo, precio) values ('Bentley', 'Continental Flying Spur', 30426);
insert into coches (marca, modelo, precio) values ('Honda', 'Accord', 12068);
insert into coches (marca, modelo, precio) values ('BMW', '3 Series', 49487);
insert into coches (marca, modelo, precio) values ('Jeep', 'Compass', 17742);
insert into coches (marca, modelo, precio) values ('Nissan', 'Pathfinder', 19991);
insert into coches (marca, modelo, precio) values ('Infiniti', 'I', 34158);
insert into coches (marca, modelo, precio) values ('Mitsubishi', 'Sigma', 28503);
insert into coches (marca, modelo, precio) values ('Cadillac', 'SRX', 44082);
insert into coches (marca, modelo, precio) values ('Saab', '9000', 13258);
insert into coches (marca, modelo, precio) values ('Ford', 'Bronco', 41691);
insert into coches (marca, modelo, precio) values ('Pontiac', 'Bonneville', 41182);
insert into coches (marca, modelo, precio) values ('Mazda', 'Protege', 15130);
insert into coches (marca, modelo, precio) values ('Dodge', 'Ram Wagon B250', 39983);
insert into coches (marca, modelo, precio) values ('Ford', 'Econoline E150', 27794);
insert into coches (marca, modelo, precio) values ('Honda', 'Prelude', 36721);
